name: Terraform destroy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-west-1"
  TF_VERSION: "1.5.0"
  
permissions:
  id-token: write
  contents: write
  pull-requests: write
  
jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::877786395093:role/github-oidc-vamsee
          aws-region: us-west-1

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Initialize Terraform
      - name: Terraform Init
        run: |
          cd Infra
          terraform init
      # Validate Terraform configuration
      - name: Terraform Validate
        run: |
          cd Infra
          terraform validate
      # Run Terraform Plan to destroy
      - name: Terraform Plan Destroy
        run: |
          cd Infra
          terraform plan -destroy -var-file="../environments/dev/terraform.tfvars" -out=tfplan
      # Run Terraform Apply to destroy
      - name: Terraform Apply Destroy
        if: github.ref == 'refs/heads/main'
        run: |
          cd Infra
          terraform apply -auto-approve tfplan
